const mockVolunteers = [
  {
    id: 1,
    firstName: 'Reem',
    lastName: 'Ben David',
    phoneNumber: 0546202454,
    email: 'reem.programmer@gmail.com',
    password: '123456',
    gender: 'male',
    verified: true,
    isActive: true,
    isManager: true,
    dateOfBirth: '10/08/1996',
    city: 'petah-tikwa',
    homeAddress: "brande ze'ev 49",
    groupId: 4,
  },
  {
    id: 2,
    firstName: 'Shil',
    lastName: 'Ravi',
    phoneNumber: 0501234567,
    email: 'shil.ravi@gmail.com',
    password: '123456',
    gender: 'female',
    verified: true,
    isActive: true,
    isManager: false,
    dateOfBirth: '10/08/1996',
    city: 'petah-tikwa',
    homeAddress: "brande ze'ev 49",
    groupId: 3,
  },
];
